Game Title: Pokemon Unite

Game Object 1: Pikachu
*Attributes
- Name: Pikachu
- Role: Attacker
- Holowear: Hip Hop Style
- Map: Theia Sky Ruins
- Offense: Choice Specs
- HP
- Attack
- Special Attack
- Speed
- Defense
- Mana
- Special Defense
- Damage
- Skills
- Range
- Ability
- Move Set

*Methods
- Basic Attack
- Thunder Shock
- Electro Web
- Thunder
- Electro Ball
- Thunderbolt
- Volt Tackle
- Thunderstorm
- Evolution
- Cooldown

Game Object 2: Absol
*Attributes
- Name: Absol
- Role: Speedster
- Holowear: Sweet Style
- Map: Theia Sky Ruins
- HP
- Attack
- Special Attack
- Speed
- Defense
- Mana
- Special Defense
- Damage
- Skills
- Range
- Ability
- Move Set
- Cooldown
- Type of Game

*Methods
- Standars Attack
- Feint
- Slash
- Pursuit
- Night Slash
- Sucker Punch
- Psycho Cut
- Midnight Slash
- Evolution

Game Object 3: Charizard
*Attributes
- Name: Charizard
- Role: All Rounder
- Holowear: Captain Style
- Map: Theia Sky Ruins
- HP
- Attack
- Special Attack
- Speed
- Defense
- Mana
- Special Defense
- Damage
- Skills
- Range
- Ability
- Move Set
- Cooldown

*Methods
- Standars Attack
- Flame Burst
- Fire Spin
- Flamethrower
- Fire Punch
- Fire Blast
- Flare Blitz
- Seismic Slam

Game Object 4: Urshifu
*Attributes
- Name: Urshifu
- Role: All Rounder
- Holowear: Captain Style
- Map: Theia Sky Ruins
- HP
- Attack
- Special Attack
- Speed
- Defense
- Mana
- Special Defense
- Damage
- Skills
- Range
- Ability
- Move Set
- Cooldown

*Methods
- Rock Smash
- Headbutt
- Wicked Blow
- Surging Strikes
- Throat Chop
- Liquidation
- Flowing Fists
- Elbow Fist

Game Object 5: Dragapult
*Attributes
- Name: Pikachu
- Role: Attacker
- Holowear: Scientist Style
- Map: Theia Sky Ruins
- Items: Choice Specs
- HP
- Attack
- Special Attack
- Speed
- Defense
- Mana
- Special Defense
- Damage
- Skills
- Range
- Ability
- Move Set
- Cooldown

*Methods
- Standard Attack
- Astonish
- Quick Attack
- Dragon Dance
- Phantom Force
- Dragon Breath
- Shadow Ball
- Dreep and Destroy

Game Object 6: Intelion
*Attributes
- Name: Pikachu
- Role: Attacker
- Holowear: Hip Hop Style
- Map: Theia Sky Ruins
- Items: Choice Specs
- HP
- Attack
- Special Attack
- Speed
- Defense
- Mana
- Special Defense
- Damage
- Skills
- Range
- Ability
- Move Set
- Cooldown

*Methods
- Basic Attack
- Water Gun
- Tearful Look
- Fell Stinger
- Acrobatics
- Snipe Shot
- Liquidation
- Azure Spy Vision

Game Object 7: Zeraora
*Attributes
- Name: Zeraora
- Role: Speedster
- Holowear: Hip Hop Style
- Map: Theia Sky Ruins
- Offense: Choice Specs
- HP
- Attack
- Special Attack
- Speed
- Defense
- Mana
- Special Defense
- Damage
- Skills
- Range
- Ability
- Move Set

*Methods
- Standard Attack
- Agility
- Splash
- Spark
- Volt Switch
- Discharge
- Wild Charge
- Plasma Gate
- Evolution
- Cooldown

Game Objects:

- Aegislash
- Alolan Ninetails
- Armarouge
- Azamarill
- Blastoise
- Blaziken
- Blissey
- Buzzwole
- Ceruledge
- Chandelure
-Cinderace
- Clefable
- Comfey
- Cramorant
- Crustle
- Dragonite
- Goodra
- Leafon
